### ISSUE TITLE
Error when setting up Docker image of 3DUnet with GPU support

### ISSUE THREAD

**Issue by Eddymorphling** [HenriquesLab/DL4MicEverywhere#24]
Hi,
Just tried running the Docker GUI (followed all instructions) to run the 3DUNET notebook with GPU support and ended up with the following error when building the Docket image. Any clue what could be wrong? Thank you.

![image](https://github.com/HenriquesLab/DL4MicEverywhere/assets/67712116/dc31fe3e-d6d8-4cc9-98bc-d046e78f81f7)

**Comment by Eddymorphling** [comment]
Edit: Adding some more context. I have an NVIDIA TITAN X Pascal GPU with the necessary NVIDIA/CUDA/cuDNN drivers setup on a Win10 PC.

**Comment by jinxsfe** [comment]
@esgomezm 
![Screenshot 2023-11-21 151908](https://github.com/HenriquesLab/DL4MicEverywhere/assets/121477741/e725da5d-05b3-43fe-a43a-3efde14a864f) I also meet same. do you have any ideas for that? appreciate

**Comment by ctr26** [comment]
Does this fail?docker run --rm --gpus all nvidia/cuda:11.8.0-base-ubuntu22.04 nvidia-smiOn 21 Nov 2023, at 20:22, jinxsfe ***@***.***> wrote:﻿
@esgomezm
 I also meet same. do you have any ideas for that? appreciate

**Comment by ctr26** [comment]
Are you running as admin/sudo?On 21 Nov 2023, at 20:28, Craig Russell ***@***.***> wrote:﻿Does this fail?docker run --rm --gpus all nvidia/cuda:11.8.0-base-ubuntu22.04 nvidia-smiOn 21 Nov 2023, at 20:22, jinxsfe ***@***.***> wrote:﻿
@esgomezm
 I also meet same. do you have any ideas for that? appreciate

**Comment by Eddymorphling** [comment]
`docker run --rm --gpus all nvidia/cuda:11.8.0-base-ubuntu22.04 nvidia-smi` This does fail. 

I also tried in admin/sudo mode `sudo -E bash launch.sh` and it fails too.

**Comment by Eddymorphling** [comment]
@ctr26 Is [this  ](https://forums.developer.nvidia.com/t/wsl-modulus-docker-run-error-libnvidia-ml-so-1-file-exists-unknown/256058)related?

**Comment by ctr26** [comment]
https://github.com/NVIDIA/nvidia-docker/issues/1551

Maybe this is? @IvanHCenalmor

**Comment by Eddymorphling** [comment]
Thanks for the referral. New to using docker. How do I identify the image ID to run the following code block as mentioned in the link.
```

FROM <the image you care about>
RUN umount /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1 && \
    rm -rf /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
```

**Comment by ctr26** [comment]
If this is the fix specifically on windows WSL itd have to be upstreamed as an actual bug fix.

**Comment by ctr26** [comment]
Otherwise if you're feeling brave 

https://github.com/HenriquesLab/DL4MicEverywhere/blob/main/Dockerfile

You'd have to add the code to (I'm guessing) line 3 in this file.

**Comment by Eddymorphling** [comment]
Thanks. I will have to wait as I am not sure how to implement the fix.

**Comment by IvanHCenalmor** [comment]
Hi @Eddymorphling and @jinxsfe ,
I will try to replicate this issue in the Windows workstation that we have and to solve it.

@ctr26 and @Eddymorphling , thanks a lot for providing those links and feedback 🙏 ❤️ 

In both issues (the one given by @Eddymorphling  [here](https://forums.developer.nvidia.com/t/wsl-modulus-docker-run-error-libnvidia-ml-so-1-file-exists-unknown/256058/7) and the one given by @ctr26 [here](https://github.com/NVIDIA/nvidia-docker/issues/1551#issuecomment-1094266607) or [here](https://github.com/NVIDIA/nvidia-docker/issues/1551#issuecomment-1590550991) ) they mention that the problem is related with some 'ghost' files are automatically injected in the containerization (maybe because of using the default nvidia image [mentioned here](https://github.com/NVIDIA/nvidia-docker/issues/1551#issuecomment-938433797)). And the solution for this can be to remove those files inside the container. Actually the last part of the error that you are getting is `...x86_64-linux-gnu/libnvidia-ml.so.1: file exists: unknown`. Which is one of the files that is removed in this proposal.

I will try to add these lines in the Dockerfile from the proposal and check if the issue can be solved with this or a similar command (that do not need to remove so many files):

  ```
  RUN rm -rf \
      /usr/lib/x86_64-linux-gnu/libcuda.so* \
      /usr/lib/x86_64-linux-gnu/libnvcuvid.so* \
      /usr/lib/x86_64-linux-gnu/libnvidia-*.so* \
      /usr/local/cuda/compat/lib/*.515.65.01
  ``` 

Also they mention [here](https://github.com/NVIDIA/nvidia-docker/issues/1551#issuecomment-934188070) that the installation  of `cuda-toolkit` apart from `nvidia-cuda-toolkit` might be needed. That is something I also need to check.

In any case, I will try it as soon as I can and I will comment with you the results that I get.

Again thanks a lot for the feedback! 🫶

**Comment by IvanHCenalmor** [comment]
Okey, so still not fixed, but I want to share with you the updates that I have.

I tried to remove the files in `/usr/lib/x86_64-linux-gnu`, but apparently by just adding that command they are not removed and the error still persist. 

I checked a lighter version of the Dockerfile with just the building from the nvidia image and some minor installations. To check at what point did these files appear and if they could be removed in this lighter Dockerfile. With this new Dockerfile, there was no problem neither when building it nor running  it. And after checking, the files were inside the container, so I assume that those files are not the ones giving the error. Additionally, I have not been able to remove them, so I decided to change the strategy. 

I continued from this lighter Dockerfile, adding step by step al the lines that I commented to check which one created the problem and apparently, the error appears from installing `nvidia-cuda-toolkit' inside the Dockerfile [in this line](https://github.com/HenriquesLab/DL4MicEverywhere/blob/a957b618e3d9dd1c27fe16eec55d5cded5b3f1dd/Dockerfile#L24). This error does not happen when building the image (because it is actually built) but when running it. 

Therefore, I decided tried to add (in the actual Dockefile with all the code) `cuda-toolkit` within `nvidia-cuda-toolkit` as suggested [here](https://github.com/NVIDIA/nvidia-docker/issues/1551#issuecomment-934188070). The error still remained, so I tried to remove the `nvidia-cuda-toolkit` from the Dockerfile installation, just leaving  `cuda-toolkit`. Removing the installation of the `nvidia-cuda-toolkit` library (keeping the rest of the code in the Dockerfile) **SOLVED** the error, **BUT** without the `nvidia-cuda-toolkit` library, TensorFlow is not able to use or initialize the GPUs.

> Everything on TensorFlow is correctly installed and when running `tf.test.is_built_with_cuda()` is returns `True`, but when running `tf.config.list_physical_devices("GPU")` it return an empty list `[]`. It also gives a warnings explaining the problem:
>```  ```

To check if everything else was correctly installed, I used the [Docker image from Pytorch](https://hub.docker.com/layers/pytorch/pytorch/1.8.0-cuda11.1-cudnn8-runtime/images/sha256-653c0570f00a9d9ad099279553b491df66a71a815610e1be76f21cdd305adcbe?context=explore) to see if the GPUs were working and it actually works without any problem.

So, as a conclusion until know is that the problem is with the `nvidia-cuda-toolkit` library, that is the one causing the error, but that is also needed for the TensorFlow library to be able to use the GPUs. So here is a big conflict. 

Now that I now that the problem is with that library and not with the file itself, I think that I have an idea of what I will try to change to fix this problem. I think that the origin of this problem might be because the paths to that library are not correctly configured or linked, so what I will try now is to check if the problem is with the PATHs in the docker image or on the local machine. 

I will continue informing you on the progress and if you have any idea or feedback of the progress until know I will bee glad to read it 😄

**Comment by ctr26** [comment]
If we use conda to install the cudatoolkit then you won't need to use apt-get to install it.

**Comment by ctr26** [comment]
Is this only testable on windows?

**Comment by IvanHCenalmor** [comment]
Yeaaah, on the Linux machine works perfectly. It is when it comes to Windows that gives problems with `nvidia-cuda-toolkit`.

**Comment by IvanHCenalmor** [comment]
Here I attach you the feedback that I got in a terminal that was run inside the docker container that was built with `cuda-toolkit` and not `nvidia-cuda-toolkit`. Here there is the output from `ls /usr/lib/x86_64-linux-gnu` and the output of checking the TensorFlow GPU configuration: [output.txt](https://github.com/HenriquesLab/DL4MicEverywhere/files/13443311/output.txt)

**Comment by esgomezm** [comment]
Hey @Eddymorphling 

We have considerably updated the tool and this issue should be solved. Could you give it a try please?

**Comment by IvanHCenalmor** [comment]
Hi @Eddymorphling ,

We haven't heard back from you in a while, so we’re going to close this issue for now. If you encounter any further issues or have any questions, please feel free to reopen this issue or create a new one. We’re here to help!

Thanks for your understanding,
Iván
